### PR TITLE
Testing mid backend integration

### LINKED ISSUE #1: Develop REST API Interface for Dashboard
Identify existing data entry fields for the document workflow to pass to the backend for useful data aggregation. Then, work with the backend and frontend teams to develop and interface to pass the aggregate data from the database to the frontend dashboard.

### LINKED ISSUE #2: Update REST API to Communicate Appropriate Data
Update the current REST API to be a bridge between our frontend and backend by properly passing requested data such as scores, reviewers, etc. for the backend to aggregate, and for the frontend to render.

### LINKED ISSUE #3: Update Database to Store Aggregated Statistics
Update the existing Teedy database to include a new table that will store aggreagted statistics in the backend which will allow us to pull from and display statistics to the frontend

### LINKED ISSUE #4: Update frontend to display statistics
Update HTML, CSS, and Javascript files to display a statistics dashboard using the new backend aggregated statistics

### PR DESCRIPTION
**Pull request by stevnzhang**
Code supports backend of the review dashboard feature by creating new classes and updating the database, sending information from the database toward the frontend. Resolves #1. Resolves #2. Resolves #3. Resolves #4.

### CODE REVIEW

**Review by coleman-isner-cmu — CHANGES_REQUESTED** [review]
Please delete the commented out  code and remove console.logs. Thank you! Looks good otherwise.

**Review by alexisaxon — APPROVED** [review]
LGTM

**Review by Leinard0 — APPROVED** [review]
LGTM

**Review by coleman-isner-cmu — APPROVED** [review]
Great work. Thank you for making the changes.

**Review by teresa-y — APPROVED** [review]
looks great!

**Pull request merged**
